Repository 21-The-julge/the_julge, pull requests merged in 2024-06, with the labels that each got.

#192 feat 사소한 오류 수정 및 에러 페이지 추가
  public/images/ic_logo.svg
  src/common/components/Gnb/GlobalNavigationBar.tsx
  src/page-layout/EditMyShopLayout/component/EditMyShop/EditMyShop.tsx
  src/page-layout/ErrorPageLayout/ErrorLayout.module.scss
  src/page-layout/ErrorPageLayout/ErrorLayout.tsx
  src/page-layout/MyShopLayout/component/MyShop/ShowMyShop/ShowMyShop.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/PostContainer/PostContainer.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/RegisteredMyShop.module.scss
  src/page-layout/MyShopLayout/type.ts
  src/page-layout/NoticesLayout/components/NoticeDetailInfo/NoticeDetailInfo.tsx
  src/pages/404.tsx
  src/pages/edit-my-shop/index.tsx
  src/pages/login/index.tsx
  src/pages/register-my-shop/index.tsx
  src/pages/shops/index.tsx
  src/pages/shops/post-notice.tsx
  src/pages/sign-up/index.tsx
  src/pages/users/[userId]/edit/index.tsx
  src/shared/apis/apiType.ts
  src/shared/components/Post/Post.module.scss
  src/shared/components/Post/Post.tsx
  src/shared/components/Post/Skeleton/PostSkeleton.module.scss
Labels: feat, hotfix

#194 fix: 새로고침 시 쿼리 스트링이 초기화 되는 문제 해결
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.tsx
Labels: hotfix

#196 refactor: Drag Slider 구현
  src/page-layout/NoticesLayout/components/DragSlider/DragSlider.module.scss
  src/page-layout/NoticesLayout/components/DragSlider/DragSlider.tsx
  src/page-layout/NoticesLayout/components/DragSlider/index.ts
  src/page-layout/NoticesLayout/components/PersonalNoticeList/PersonalNoticeList.tsx
Labels: feat
