Repository 21-The-julge/the_julge, pull requests merged in 2024-04, with the labels that each got.

#3 [build] sass - package 파일 수정
  .eslintcache
  package-lock.json
  package.json
Labels: hotfix

#6 [hotfix] eslint 캐쉬 삭제
  .eslintcache
  .gitignore
Labels: hotfix

#12 feat: api로 불러오는 이미지 전체 허용
  next.config.mjs
Labels: feat

#21 fix: mixin 화면 사이즈 수정
  src/styles/mixin.scss
Labels: refactor

#25 [feat] reset.scss 수정 및 globals값 zindex font 추가
  .husky/pre-commit
  next.config.mjs
  src/pages/_app.tsx
  src/shared/components/RootLayout/RootLayout.tsx
  src/styles/fonts.scss
  src/styles/globals.scss
  src/styles/reset.scss
  src/styles/zindex.scss
Labels: feat

#31 [hotfix] font url 수정
  next.config.mjs
  src/common/components/Input/Input.module.scss
  src/common/components/Input/Input.tsx
  src/pages/login/index.tsx
  src/styles/fonts.scss
  src/styles/reset.scss
Labels: bug, hotfix

#18 feat: instance 생성
  .env
  src/pages/api/axiosInstance.ts
  src/pages/api/hello.ts
Labels: feat

#35 feat: 폰트 추가
  src/styles/fonts.scss
Labels: feat

#40 feat: reset.scss에 style 추가
  src/styles/reset.scss
Labels: feat

#32 feat: 버튼 컴포넌트 구현
  .eslintrc.json
  src/common/components/Button/Button.module.scss
  src/common/components/Button/Button.tsx
  src/common/components/index.ts
  src/styles/colors.scss
  src/styles/fonts.scss
Labels: feat

#50 feat: date-fns 라이브러리 추가
  package-lock.json
  package.json
Labels: feat

#36 feat: post 공통 컴포넌트 제작, 스켈레톤
  .env
  public/images/ic_arrowUp.svg
  public/images/ic_clock.svg
  public/images/ic_location.svg
  src/pages/index.module.scss
  src/pages/index.tsx
  src/shared/components/Post/HighPriceRateBadge/HighPriceRateBadge.module.scss
  src/shared/components/Post/HighPriceRateBadge/HighPriceRateBadge.tsx
  src/shared/components/Post/NoticeMessage/NoticeMessage.module.scss
  src/shared/components/Post/NoticeMessage/NoticeMessage.tsx
  src/shared/components/Post/Post.module.scss
  src/shared/components/Post/Post.tsx
  src/shared/components/Post/Skeleton/PostSkeleton.module.scss
  src/shared/components/Post/Skeleton/PostSkeleton.tsx
  src/shared/components/Post/utils/addComma.ts
  src/shared/components/index.ts
  src/shared/utils/getDate.ts
Labels: feat

#57 [refactor] index 파일 수정 및 삭제, Post 컴포넌트 props 추가
  src/pages/index.module.scss
  src/pages/index.tsx
  src/shared/components/Post/Post.tsx
  src/shared/components/Post/Skeleton/PostSkeleton.tsx
Labels: refactor

#43 feat: Toast 구현
  package-lock.json
  package.json
  src/common/components/Toast/constants/toastType.ts
  src/common/components/Toast/utils/openToast.ts
  src/pages/_app.tsx
Labels: feat

#41 feat: 모달 구현
  src/common/components/Modal/AlertModal/AlertModal.module.scss
  src/common/components/Modal/AlertModal/AlertModal.tsx
  src/common/components/Modal/ConfirmModal/ConfirmModal.module.scss
  src/common/components/Modal/ConfirmModal/ConfirmModal.tsx
  src/common/components/Modal/Modal.module.scss
  src/common/components/Modal/Modal.tsx
  src/common/components/Modal/ModalPortal.tsx
  src/common/components/Modal/WarnModal/WarnModal.module.scss
  src/common/components/Modal/WarnModal/WarnModal.tsx
  src/common/components/Modal/hooks/useIsMounted.ts
  src/common/components/Modal/hooks/useOutsideClick.ts
  src/pages/_document.tsx
  src/styles/fonts.scss
  src/styles/reset.scss
Labels: feat

#38 feat: badge 컴포넌트 제작
  src/shared/components/Badge/Badge.module.scss
  src/shared/components/Badge/Badge.tsx
Labels: feat

#64 hotfix: badge close svg import 위치 수정 완료
  src/shared/components/Badge/Badge.tsx
Labels: bug, hotfix

#61 feat filter 컴포넌트 생성
  .eslintrc.json
  package-lock.json
  package.json
  src/common/components/Button/Button.module.scss
  src/common/components/Button/Button.tsx
  src/page-layout/NoticesLayout/components/Filter/AddressSelector/AddressSelector.module.scss
  src/page-layout/NoticesLayout/components/Filter/AddressSelector/AddressSelector.tsx
  src/page-layout/NoticesLayout/components/Filter/AddressSelector/index.ts
  src/page-layout/NoticesLayout/components/Filter/FieldSet/FieldSet.module.scss
  src/page-layout/NoticesLayout/components/Filter/FieldSet/FieldSet.tsx
  src/page-layout/NoticesLayout/components/Filter/FieldSet/index.ts
  src/page-layout/NoticesLayout/components/Filter/Filter.module.scss
  src/page-layout/NoticesLayout/components/Filter/Filter.tsx
  src/page-layout/NoticesLayout/components/Filter/StartDatePicker/StartDatePicker.tsx
  src/page-layout/NoticesLayout/components/Filter/StartDatePicker/index.ts
  src/page-layout/NoticesLayout/components/index.ts
  src/pages/notices/index.tsx
  src/shared/utils/remove.ts
Labels: feat

#59 feat: Gnb, Notification Modal, Footer 제작
  src/common/components/Footer/Footer.module.scss
  src/common/components/Footer/Footer.tsx
  src/common/components/Gnb/Gnb.module.scss
  src/common/components/Gnb/Gnb.tsx
  src/common/components/Gnb/GnbComponents/UserAction.module.scss
  src/common/components/Gnb/GnbComponents/UserAction.tsx
  src/common/components/NotificationModal/NotificationModal.module.scss
  src/common/components/NotificationModal/NotificationModal.tsx
  src/common/components/NotificationModal/NotificationModalComponents/AlertCardModal.module.scss
  src/common/components/NotificationModal/NotificationModalComponents/AlertCardModal.tsx
  src/common/components/NotificationModal/NotificationModalComponents/CreateCards.module.scss
  src/common/components/NotificationModal/NotificationModalComponents/CreateCards.tsx
  src/common/components/NotificationModal/types.ts
  src/common/components/gnb/Gnb.tsx
  src/page-layout/AuthLayout/component/Search/SearchLayout.module.scss
  src/page-layout/AuthLayout/component/Search/SearchLayout.tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
  src/shared/components/RootLayout/RootLayout.tsx
  src/shared/hooks/getAlertCardModalData.tsx
  src/shared/hooks/getAuth.tsx
  src/shared/hooks/getNotificationData.tsx
  src/styles/colors.scss
Labels: feat

#72 feat tanstack query 세팅
  package-lock.json
  package.json
  src/page-layout/NoticesLayout/components/Filter/Filter.tsx
  src/pages/_app.tsx
Labels: feat, hotfix

#54 [feat] input component 제작
  src/common/components/FieldGroup/FieldGroup.module.scss
  src/common/components/FieldGroup/FieldGroup.tsx
  src/common/components/Input/Input.module.scss
  src/common/components/Input/Input.tsx
  src/common/components/InputField/InputField.module.scss
  src/common/components/InputField/InputField.tsx
  src/common/components/InputField/index.ts
  src/common/components/InputField/parts/ErrorMessage.module.scss
  src/common/components/InputField/parts/ErrorMessage.tsx
  src/common/components/InputField/parts/Input.module.scss
  src/common/components/InputField/parts/Input.tsx
  src/common/components/InputField/parts/Label.module.scss
  src/common/components/InputField/parts/Label.tsx
  src/common/components/InputField/parts/PrefixElement.tsx
  src/common/components/InputField/parts/SuffixElement.module.scss
  src/common/components/InputField/parts/SuffixElement.tsx
  src/common/components/index.ts
  src/common/constants/index.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
  src/pages/sign-up/index.tsx
  src/styles/_colors.scss
  src/styles/_fonts.scss
  src/styles/_mixin.scss
  src/styles/_zindex.scss
  src/styles/globals.scss
Labels: feat

#68 hotfix: GNB 코드 오류 수정
  src/common/components/Gnb/GnbComponents/UserAction.tsx
  src/shared/hooks/getAuth.tsx
Labels: hotfix

#73 hitfix: api 오타 수정 및 간단한 코드 수정
  src/shared/apis/api-hooks/apiUtills.ts
  src/shared/apis/api-hooks/index.ts
  src/shared/apis/api-hooks/useAlerts.ts
  src/shared/apis/api-hooks/useApplications.ts
  src/shared/apis/api-hooks/useAuthentications.ts
  src/shared/apis/api-hooks/useImages.ts
  src/shared/apis/api-hooks/useNotices.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/api-hooks/useUsers.ts
  src/shared/apis/api-hooks/users.ts
  src/shared/apis/axiosInstance.ts
  src/shared/hooks/getNotificationData.tsx
Labels: hotfix

#75 chore: eslint rule 추가
  .eslintrc.json
Labels: hotfix

#55 feat table 컴포넌트 제작
  src/common/components/Table/Table.tsx
  src/common/components/Table/table.module.scss
Labels: feat

#80 refactor: table 컴포넌트 props type 변경
  src/common/components/Table/Table.tsx
Labels: hotfix, refactor

#81 refactor: api tanstack-query로 교체 및 params 타입 모듈화
  src/common/components/NotificationModal/NotificationModal.tsx
  src/shared/apis/api-hooks/apiUtills.ts
  src/shared/apis/api-hooks/index.ts
  src/shared/apis/api-hooks/useAlerts.ts
  src/shared/apis/api-hooks/useApplications.ts
  src/shared/apis/api-hooks/useAuthentications.ts
  src/shared/apis/api-hooks/useImages.ts
  src/shared/apis/api-hooks/useNotices.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/api-hooks/useUsers.ts
  src/shared/apis/apiType.ts
  src/shared/hooks/getNotificationData.tsx
Labels: refactor

#66 feat: pagination 컴포넌트 제작
  public/images/ic_arrow_double_left.svg
  public/images/ic_arrow_double_right.svg
  public/images/ic_arrow_left.svg
  public/images/ic_arrow_right.svg
  src/shared/components/Pagination/Pagination.module.scss
  src/shared/components/Pagination/Pagination.tsx
  src/shared/hooks/usePagination.ts
Labels: feat

#82 [feat] Dropdown 및 Fieldgroup 컴포넌트 제작
  .husky/pre-commit
  public/images/ic_triangleDown.svg
  src/common/components/FieldGroup/Dropdown/Dropdown.module.scss
  src/common/components/FieldGroup/Dropdown/Dropdown.tsx
  src/common/components/FieldGroup/FieldGroup.module.scss
  src/common/components/FieldGroup/FieldGroup.tsx
  src/common/components/FieldGroup/InputField/InputField.module.scss
  src/common/components/FieldGroup/InputField/InputField.tsx
  src/common/components/FieldGroup/Textarea/Textarea.module.scss
  src/common/components/FieldGroup/Textarea/Textarea.tsx
  src/common/components/FieldGroup/index.ts
  src/common/components/FieldGroup/parts/ErrorMessage.module.scss
  src/common/components/FieldGroup/parts/ErrorMessage.tsx
  src/common/components/FieldGroup/parts/Input.module.scss
  src/common/components/FieldGroup/parts/Input.tsx
  src/common/components/FieldGroup/parts/Label.module.scss
  src/common/components/FieldGroup/parts/Label.tsx
  src/common/components/FieldGroup/parts/PrefixElement.tsx
  src/common/components/FieldGroup/parts/SuffixIcon.module.scss
  src/common/components/FieldGroup/parts/SuffixIcon.tsx
  src/common/components/FieldGroup/parts/SuffixUnit.module.scss
  src/common/components/FieldGroup/parts/SuffixUnit.tsx
  src/common/components/FieldGroup/parts/TriangleUpDown.module.scss
  src/common/components/FieldGroup/parts/TriangleUpDown.tsx
  src/common/components/FieldGroup/parts/index.ts
  src/common/components/FieldGroup/type.ts
  src/common/components/InputField/index.ts
  src/common/components/InputField/parts/SuffixElement.module.scss
  src/common/components/InputField/parts/SuffixElement.tsx
  src/common/components/Modal/AlertModal/AlertModal.tsx
  src/common/components/Modal/ConfirmModal/ConfirmModal.tsx
  src/common/components/Modal/ModalPortal.tsx
  src/common/components/Modal/WarnModal/WarnModal.tsx
  src/common/components/index.ts
  src/common/constants/index.ts
  src/common/hooks/useIsMounted.ts
  src/common/hooks/useOutsideClick.ts
  src/pages/_app.tsx
  src/pages/login/index.tsx
Labels: feat

#83 feat : 가게 정보 상세 페이지 제작
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  package-lock.json
  package.json
  public/images/defaultImg.svg
  src/page-layout/MyShopLayout/component/MyShop/MyShop.module.scss
  src/page-layout/MyShopLayout/component/MyShop/MyShop.tsx
  src/page-layout/MyShopLayout/component/MyShop/ShopRegister/ShopRegister.module.scss
  src/page-layout/MyShopLayout/component/MyShop/ShopRegister/ShopRegister.tsx
  src/page-layout/MyShopLayout/component/MyShop/ShowMyShop/ShowMyShop.tsx
  src/page-layout/MyShopLayout/component/MyShop/ShowMyShop/ShowMyshop.module.scss
  src/page-layout/MyShopLayout/component/RegisteredShop/Register/Register.module.scss
  src/page-layout/MyShopLayout/component/RegisteredShop/Register/Register.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisterdShop.module.scss
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisterdShop.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/PostContainer/PostContainer.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/RegisteredMyShop.module.scss
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/RegisteredMyshop.tsx
  src/page-layout/MyShopLayout/hooks/useGetShopData.ts
  src/page-layout/MyShopLayout/type.ts
  src/pages/my-shop/index.tsx
  src/shared/components/Post/HighPriceRateBadge/HighPriceRateBadge.module.scss
  src/shared/components/Post/HighPriceRateBadge/HighPriceRateBadge.tsx
  src/shared/components/Post/Post.module.scss
  src/shared/components/Post/Post.tsx
  src/shared/components/Post/Skeleton/PostSkeleton.module.scss
  src/shared/components/Post/Skeleton/PostSkeleton.tsx
  src/shared/components/Post/utils/addComma.ts
  src/shared/components/RootLayout/RootLayout.module.scss
  src/shared/components/RootLayout/RootLayout.tsx
  src/shared/utils/getDate.ts
  src/shared/utils/getFormatDateTimeRange.ts
  src/styles/reset.scss
Labels: feat

#85 hotfix: gnb, footer css 디자인 수정
  src/common/components/Footer/Footer.module.scss
  src/common/components/Footer/Footer.tsx
  src/common/components/Gnb/Gnb.module.scss
  src/common/components/Gnb/Gnb.tsx
  src/common/components/gnb/Gnb.tsx
  src/shared/components/RootLayout/RootLayout.tsx
Labels: hotfix

#91 [hotfix] export 방식 및 suffixUnit 수정
  src/common/components/FieldGroup/parts/SuffixUnit.tsx
  src/common/components/index.ts
Labels: hotfix

#94 hotfix: svg 파일 때문에 발생한 콘솔 에러 제거
  public/images/ic_arrowUp.svg
  public/images/ic_check.svg
  public/images/ic_clock.svg
  public/images/ic_close.svg
  public/images/ic_envelope-square.svg
  public/images/ic_facebook-square.svg
  public/images/ic_instagram.svg
  public/images/ic_location.svg
  public/images/ic_notification.svg
  public/images/ic_search.svg
  public/images/ic_triangleDown.svg
  public/images/ic_warn.svg
  public/images/logo.svg
Labels: hotfix

#92 hotfix: zustand 설치 및 적용, getAuth 기능 수정 및 api 코드 수정
  package-lock.json
  package.json
  src/common/components/FieldGroup/type.ts
  src/pages/index.tsx
  src/shared/apis/api-hooks/useAlerts.ts
  src/shared/apis/api-hooks/useApplications.ts
  src/shared/apis/api-hooks/useAuthentications.ts
  src/shared/apis/api-hooks/useImages.ts
  src/shared/apis/api-hooks/useNotices.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/api-hooks/useUsers.ts
  src/shared/apis/axiosInstance.ts
  src/shared/hooks/getAuth.tsx
  src/shared/hooks/useUserDataStore.tsx
Labels: feat, hotfix

#99 hotfix: 오타 수정
  src/shared/apis/api-hooks/useImages.ts
  src/shared/apis/api-hooks/useNotices.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/api-hooks/useUsers.ts
Labels: hotfix

#100 [refactor] input 컴포넌트 forwardRef추가 및 restProps 추가
  src/common/components/FieldGroup/FieldGroup.tsx
  src/common/components/FieldGroup/InputField/InputField.tsx
  src/common/components/FieldGroup/parts/Input.tsx
Labels: refactor

#87 feat 전체 공고 불러오기
  src/common/components/Button/Button.module.scss
  src/common/components/FieldGroup/Dropdown/Dropdown.module.scss
  src/common/components/FieldGroup/Dropdown/Dropdown.tsx
  src/common/components/FieldGroup/InputField/InputField.tsx
  src/common/constants/index.ts
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.module.scss
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.tsx
  src/page-layout/NoticesLayout/components/AllNotices/index.ts
  src/page-layout/NoticesLayout/components/AllNoticesSkeleton/AllNoticesSkeleton.module.scss
  src/page-layout/NoticesLayout/components/AllNoticesSkeleton/AllNoticesSkeleton.tsx
  src/page-layout/NoticesLayout/components/AllNoticesSkeleton/index.ts
  src/page-layout/NoticesLayout/components/Filter/AddressSelector/AddressSelector.tsx
  src/page-layout/NoticesLayout/components/Filter/Filter.module.scss
  src/page-layout/NoticesLayout/components/Filter/Filter.tsx
  src/page-layout/NoticesLayout/components/Filter/index.ts
  src/page-layout/NoticesLayout/components/FilterBar/FilterBar.module.scss
  src/page-layout/NoticesLayout/components/FilterBar/FilterBar.tsx
  src/page-layout/NoticesLayout/components/FilterBar/index.ts
  src/page-layout/NoticesLayout/components/NoNotice/NoNotice.module.scss
  src/page-layout/NoticesLayout/components/NoNotice/NoNotice.tsx
  src/page-layout/NoticesLayout/components/NoNotice/index.ts
  src/page-layout/NoticesLayout/components/NoticeList/NoticeList.module.scss
  src/page-layout/NoticesLayout/components/NoticeList/NoticeList.tsx
  src/page-layout/NoticesLayout/components/NoticeList/index.ts
  src/page-layout/NoticesLayout/components/index.ts
  src/page-layout/NoticesLayout/type.ts
  src/pages/_app.tsx
  src/pages/notices/index.tsx
  src/pages/notices/notices.module.scss
  src/shared/components/Badge/Badge.tsx
  src/shared/hooks/useGetAllNotices.ts
  src/styles/reset.scss
Labels: feat

#97 refactor: 가게 정보 상세 페이지 반응형 수정
  src/common/components/Toast/constants/toastType.ts
  src/page-layout/MyShopLayout/component/MyShop/MyShop.module.scss
  src/page-layout/MyShopLayout/component/MyShop/ShowMyShop/ShowMyShop.tsx
  src/page-layout/MyShopLayout/component/MyShop/ShowMyShop/ShowMyshop.module.scss
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/PostContainer/PostContainer.module.scss
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/PostContainer/PostContainer.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/RegisteredMyShop.module.scss
  src/pages/_app.tsx
  src/pages/my-shop/index.tsx
  src/shared/components/Post/HighPriceRateBadge/HighPriceRateBadge.tsx
  src/shared/components/Post/Post.module.scss
  src/shared/components/Post/Post.tsx
  src/shared/components/Post/Skeleton/PostSkeleton.tsx
Labels: refactor

#103 hotfix: input field가 className이 적용되도록 수정
  src/common/components/FieldGroup/InputField/InputField.tsx
  src/page-layout/NoticesLayout/components/Filter/StartDatePicker/StartDatePicker.module.scss
  src/page-layout/NoticesLayout/components/Filter/StartDatePicker/StartDatePicker.tsx
Labels: hotfix

#109 hotfix: zustand 및 getAuth 수정
  src/common/components/Gnb/Gnb.module.scss
  src/common/components/Gnb/GnbComponents/UserAction.tsx
  src/pages/index.tsx
  src/shared/apis/api-hooks/useAlerts.ts
  src/shared/apis/api-hooks/useApplications.ts
  src/shared/apis/api-hooks/useNotices.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/api-hooks/useUsers.ts
  src/shared/apis/apiType.ts
  src/shared/apis/axiosInstance.ts
  src/shared/hooks/getAuth.tsx
  src/shared/hooks/getUserData.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useUserDataStore.tsx
Labels: hotfix

#116 hotfix: 오류 수정
  src/common/components/Gnb/GnbComponents/UserAction.tsx
  src/shared/apis/api-hooks/useAuthentications.ts
  src/shared/hooks/getUserData.tsx
  src/shared/hooks/useUserDataStore.tsx
Labels: hotfix

#95 feat : 내 프로필 상세 페이지 제작
  public/images/ic_phone.svg
  src/page-layout/MyProfileLayout/ApplicationDetail/RegisterNotice/RegisterNotice.tsx
  src/page-layout/MyProfileLayout/ApplicationDetail/RegisterNotice/RegitserNotice.module.scss
  src/page-layout/MyProfileLayout/ApplicationDetail/ViewNotice/ViewNotice.module.scss
  src/page-layout/MyProfileLayout/ApplicationDetail/ViewNotice/ViewNotice.tsx
  src/page-layout/MyProfileLayout/MyProfile/MyProfile.tsx
  src/page-layout/MyProfileLayout/MyProfile/RegisterMyProfile/RegisterMyProfile.module.scss
  src/page-layout/MyProfileLayout/MyProfile/RegisterMyProfile/RegisterMyProfile.tsx
  src/page-layout/MyProfileLayout/MyProfile/ShowMyProfile/ShowMyProfile.module.scss
  src/page-layout/MyProfileLayout/MyProfile/ShowMyProfile/ShowMyProfile.tsx
  src/pages/my-profile/index.tsx
  src/shared/utils/getBadge.tsx
Labels: feat

#118 feat: 내 프로필 등록 공고 등록 페이지
  src/common/components/InputField/InputField.tsx
  src/page-layout/PostNoticeLayout/PostNoticeLayout.module.scss
  src/page-layout/PostNoticeLayout/PostNoticeLayout.tsx
  src/page-layout/PostNoticeLayout/components/PostNoticeForm.module.scss
  src/page-layout/PostNoticeLayout/components/PostNoticeForm.tsx
  src/page-layout/PostProfileLayout/PostProfileLayout.module.scss
  src/page-layout/PostProfileLayout/PostProfileLayout.tsx
  src/page-layout/PostProfileLayout/components/PostProfileForm.module.scss
  src/page-layout/PostProfileLayout/components/PostProfileForm.tsx
  src/pages/my-profile/postProfile/index.tsx
  src/pages/my-shop/postNotice/index.tsx
Labels: feat

#119 [feat] signin signup page 제작 - 미완성
  .eslintrc.json
  package-lock.json
  package.json
  src/common/components/InputField/InputField.tsx
  src/common/components/RadioField/RadioInput.module.scss
  src/common/components/RadioField/RadioInput.tsx
  src/common/components/index.ts
  src/common/components/parts/Label.tsx
  src/common/constants/index.ts
  src/page-layout/AuthLayout/component/AuthForm/SignInForm.module.scss
  src/page-layout/AuthLayout/component/AuthForm/SignInForm.tsx
  src/page-layout/AuthLayout/component/AuthForm/SignUpForm.tsx
  src/page-layout/AuthLayout/component/index.ts
  src/pages/login/SignInPage.module.scss
  src/pages/login/index.tsx
  src/pages/my-profile/index.tsx
  src/pages/sign-up/SignUpPage.module.scss
  src/pages/sign-up/index.tsx
  src/shared/apis/api-hooks/useAuthentications.ts
  src/shared/apis/api-hooks/useUsers.ts
  src/shared/apis/apiType.ts
Labels: feat

#124 hotfix: gnb ROUTE 연결 및 api 커스텀훅 주소 상수화
  src/common/components/Gnb/GnbComponents/UserAction.tsx
  src/common/constants/index.ts
  src/shared/apis/api-hooks/useAlerts.ts
  src/shared/apis/api-hooks/useApplications.ts
  src/shared/apis/api-hooks/useAuthentications.ts
  src/shared/apis/api-hooks/useImages.ts
  src/shared/apis/api-hooks/useNotices.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/api-hooks/useUsers.ts
Labels: hotfix

#128 chore: gitignore에 .env 파일 추가
  .gitignore
Labels: build, docs

#131 hotfix: 오류 수정 및 페이지 분리
  src/common/components/Gnb/GnbComponents/UserAction.tsx
  src/common/constants/index.ts
  src/page-layout/MyProfileLayout/MyProfile/ShowMyProfile/ShowMyProfile.tsx
  src/page-layout/MyShopLayout/component/MyShop/ShowMyShop/ShowMyShop.tsx
  src/page-layout/PostNoticeEditLayout/PostNoticeEditLayout.module.scss
  src/page-layout/PostNoticeEditLayout/PostNoticeEditLayout.tsx
  src/page-layout/PostNoticeEditLayout/components/PostNoticeEditForm.module.scss
  src/page-layout/PostNoticeEditLayout/components/PostNoticeEditForm.tsx
  src/page-layout/PostProfileEditLayout/PostProfileEditLayout.module.scss
  src/page-layout/PostProfileEditLayout/PostProfileEditLayout.tsx
  src/page-layout/PostProfileEditLayout/components/PostProfileEditForm.module.scss
  src/page-layout/PostProfileEditLayout/components/PostProfileEditForm.tsx
  src/pages/shops/[shopId].tsx
  src/pages/shops/index.tsx
  src/pages/shops/post-notice.tsx
  src/pages/users/[userId].tsx
  src/pages/users/index.tsx
  src/pages/users/post-profile.tsx
Labels: hotfix

#135 hotfix: zustand 상태 관리가 유지되도록 변경
  src/shared/hooks/useUserDataStore.tsx
Labels: hotfix

#126 fix: 알림창 스타일 수정
  src/common/components/NotificationModal/NotificationModalComponents/AlertCardModal.module.scss
  src/common/components/NotificationModal/NotificationModalComponents/CreateCards.module.scss
Labels: hotfix

#137 [refactor] signin signup page 완성
  .eslintrc.json
  public/images/ic_check.svg
  src/common/components/Dropdown/Dropdown.tsx
  src/common/components/InputField/InputField.module.scss
  src/common/components/InputField/InputField.tsx
  src/common/components/RadioField/RadioField.module.scss
  src/common/components/RadioField/RadioField.tsx
  src/common/components/RadioField/RadioInput.tsx
  src/common/components/index.ts
  src/common/components/parts/Input.module.scss
  src/common/components/parts/Radio.module.scss
  src/common/components/parts/Radio.tsx
  src/common/components/parts/RadioToggle.module.scss
  src/common/components/parts/RadioToggle.tsx
  src/common/components/parts/index.ts
  src/common/constants/index.ts
  src/page-layout/AuthLayout/apis/index.ts
  src/page-layout/AuthLayout/component/AuthForm/SignInForm.tsx
  src/page-layout/AuthLayout/component/AuthForm/SignUpForm.tsx
  src/page-layout/AuthLayout/hooks/index.ts
  src/page-layout/AuthLayout/hooks/queries/index.ts
  src/page-layout/AuthLayout/utils/index.ts
  src/pages/login/index.tsx
  src/pages/sign-up/index.tsx
  src/styles/reset.scss
Labels: refactor

#115 feat: 가게 정보 등록 페이지 구현
  .env
  public/images/ic_camera.svg
  src/common/components/Dropdown/Dropdown.tsx
  src/page-layout/MyShopLayout/component/MyShop/ShopRegister/ShopRegister.tsx
  src/page-layout/MyShopLayout/hooks/useGetShopData.ts
  src/page-layout/NoticesLayout/components/NoNotice/NoNotice.module.scss
  src/page-layout/RegisterMyShopLayout/component/RegisterMyShop/RegisterMyShop.module.scss
  src/page-layout/RegisterMyShopLayout/component/RegisterMyShop/RegisterMyShop.tsx
  src/pages/register-my-shop/index.tsx
  src/pages/shops/index.tsx
  src/shared/apis/api-hooks/useImages.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/apiType.ts
  src/shared/hooks/getUserData.tsx
  src/shared/hooks/useUserDataStore.tsx
Labels: feat

#139 hotfix: 필터 UI 및 알림창 z-index 수정
  src/common/components/Gnb/Gnb.module.scss
  src/common/components/Gnb/Gnb.tsx
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.tsx
  src/page-layout/NoticesLayout/components/Filter/Filter.module.scss
  src/page-layout/NoticesLayout/components/FilterBar/FilterBar.module.scss
Labels: hotfix

#136 feat: 공고 수정, 내 프로필 수정 페이지 기능 구현
  src/common/components/Dropdown/Dropdown.tsx
  src/page-layout/MyProfileLayout/MyProfile/ShowMyProfile/ShowMyProfile.tsx
  src/page-layout/PostNoticeEditLayout/PostNoticeEditLayout.tsx
  src/page-layout/PostNoticeEditLayout/components/PostNoticeEditForm.tsx
  src/page-layout/PostNoticeLayout/PostNoticeLayout.tsx
  src/page-layout/PostNoticeLayout/ValidateInput.tsx
  src/page-layout/PostNoticeLayout/components/PostNoticeForm.tsx
  src/page-layout/PostProfileEditLayout/PostProfileEditLayout.tsx
  src/page-layout/PostProfileEditLayout/components/PostProfileEditForm.tsx
  src/page-layout/PostProfileLayout/PostProfileLayout.tsx
  src/page-layout/PostProfileLayout/ValidateInput.tsx
  src/page-layout/PostProfileLayout/components/PostProfileForm.tsx
  src/pages/shops/[shopId]/notices/[noticeId].tsx
  src/pages/shops/[shopId]/notices/[noticeId]/edit.tsx
  src/pages/users/[userId]/edit.tsx
Labels: feat, refactor

#141 refactor: Post, AllNotices, PersonalNotices 수정
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.module.scss
  src/page-layout/NoticesLayout/components/Notices/Notices.module.scss
  src/page-layout/NoticesLayout/components/PersonalNotices/PersonalNotices.module.scss
  src/shared/components/Post/Post.module.scss
  src/shared/components/Post/Post.tsx
Labels: refactor

#120 78 feat 공고상세 페이지 제작
  src/common/constants/index.ts
  src/page-layout/NoticesLayout/components/NoticeDetailInfo/NoticeDetailButtonAndModal/NoticeDetailButtonAndModal.module.scss
  src/page-layout/NoticesLayout/components/NoticeDetailInfo/NoticeDetailButtonAndModal/NoticeDetailButtonAndModal.tsx
  src/page-layout/NoticesLayout/components/NoticeDetailInfo/NoticeDetailInfo.module.scss
  src/page-layout/NoticesLayout/components/NoticeDetailInfo/NoticeDetailInfo.tsx
  src/page-layout/NoticesLayout/components/NoticeTable/NoticeTable.module.scss
  src/page-layout/NoticesLayout/components/NoticeTable/NoticeTable.tsx
  src/page-layout/NoticesLayout/components/NoticesRecent/NoticesRecent.module.scss
  src/page-layout/NoticesLayout/components/NoticesRecent/NoticesRecent.tsx
  src/page-layout/NoticesLayout/type.ts
  src/shared/apis/api-hooks/useApplications.ts
  src/shared/components/Pagination/Pagination.tsx
  src/shared/utils/getLocalStorage.ts
  src/shared/utils/localData.ts
Labels: feat

#122 feat : 가게 정보 편집 페이지 구현
  .env
  src/page-layout/EditMyShopLayout/component/EditMyShop/EditMyShop.module.scss
  src/page-layout/EditMyShopLayout/component/EditMyShop/EditMyShop.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/RegisteredMyshop.tsx
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.module.scss
  src/pages/edit-my-shop/index.tsx
  src/shared/apis/api-hooks/useShops.ts
Labels: feat

#146 hotfix: 필터 props 삭제
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.tsx
  src/shared/hooks/useGetAllNotices.ts
Labels: hotfix

#148 refactor: 에러 제거
  package.json
  src/page-layout/EditMyShopLayout/component/EditMyShop/EditMyShop.tsx
  src/page-layout/MyShopLayout/component/RegisteredShop/RegisteredMyShop/RegisteredMyshop.tsx
  src/page-layout/NoticesLayout/components/AllNotices/AllNotices.module.scss
  src/shared/apis/apiType.ts
  src/shared/hooks/getUserData.tsx
  src/shared/utils/getLocalStorage.ts
Labels: refactor

#149 bug: notice-detail 파일 재생성
  src/pages/notice-detail/index.tsx
Labels: bug

#157 hotfix: post p태그 중복 에러 해결
  src/shared/components/Post/Post.tsx
Labels: hotfix

#161 [refactor] 공고 상세 페이지 수정
  src/page-layout/NoticesLayout/components/NoticeDetailInfo/NoticeDetailButtonAndModal/NoticeDetailButtonAndModal.tsx
Labels: refactor

#174 [refactor] signupform의 type선택 input 수정 & RegisterMyShop 기능구현
  src/common/components/Dropdown/Dropdown.module.scss
  src/common/components/Dropdown/Dropdown.tsx
  src/common/components/InputField/InputField.tsx
  src/common/components/RadioField/RadioField.tsx
  src/common/components/Textarea/Textarea.tsx
  src/common/components/parts/ErrorMessage.module.scss
  src/common/components/parts/Input.tsx
  src/common/components/parts/Radio.tsx
  src/page-layout/RegisterMyShopLayout/component/RegisterMyShop/RegisterMyShop.tsx
  src/shared/apis/api-hooks/useImages.ts
  src/shared/apis/api-hooks/useShops.ts
  src/shared/apis/apiType.ts
Labels: refactor

#177 hotfix: gnb 디자인 문제 수정
  src/common/components/Gnb/GlobalNavigationBar.module.scss
  src/common/components/NotificationModal/NotificationModal.tsx
  src/common/components/NotificationModal/NotificationModalComponents/AlertCardModal.module.scss
  src/common/components/NotificationModal/NotificationModalComponents/AlertCardModal.tsx
  src/styles/_zindex.scss
Labels: hotfix

#185 fixed: 내 프로필 수정 페이지에서 이름과 연락처안나오는 버그 수정
  src/common/components/Gnb/GlobalNavigationBar.module.scss
  src/common/components/InputField/InputField.tsx
  src/styles/_zindex.scss
Labels: bug

#186 [Hotfix] input prop 수정
  src/common/components/InputField/InputField.tsx
Labels: hotfix
